
public class admin extends javax.swing.JFrame {

	view v;
	controller c;

	public admin(controller c) {
		this.c = c;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		adminP = new javax.swing.JTextField();
		adminM = new javax.swing.JTextField();
		adminL = new javax.swing.JTextField();
		magic = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		adminTurn0 = new javax.swing.JButton();
		adminTurn1 = new javax.swing.JButton();
		adminTurn2 = new javax.swing.JButton();
		adminTurn3 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		adminSlot = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		adminOwner = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		adminPrice = new javax.swing.JTextField();
		confirm = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel1.setText("Money:");

		jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel2.setText("Player:");

		jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel3.setText("Location:");

		jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel4.setText("Status:");

		magic.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		magic.setText("Change");
		magic.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				magicActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel5.setText("Turn Change");

		adminTurn0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		adminTurn0.setText("Player 1");
		adminTurn0.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adminTurn0ActionPerformed(evt);
			}
		});

		adminTurn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		adminTurn1.setText("Player 2");
		adminTurn1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adminTurn1ActionPerformed(evt);
			}
		});

		adminTurn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		adminTurn2.setText("Player 3");
		adminTurn2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adminTurn2ActionPerformed(evt);
			}
		});

		adminTurn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		adminTurn3.setText("Player 4");
		adminTurn3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adminTurn3ActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel6.setText("Land:");

		jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel7.setText("Owner:");

		jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel8.setText("Price:");

		confirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		confirm.setText("EDIT");
		confirm.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				confirmActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(33, 33, 33)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(adminP, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												adminM, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(adminL, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(magic, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(68, 68, 68)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(adminTurn3, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(adminTurn0, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(adminTurn1, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														adminTurn2, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(58, 58, 58)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE,
																74, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(adminSlot, javax.swing.GroupLayout.PREFERRED_SIZE,
																129, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
																74, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(adminOwner,
																javax.swing.GroupLayout.PREFERRED_SIZE, 129,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
																74, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(adminPrice,
																javax.swing.GroupLayout.PREFERRED_SIZE, 129,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGap(40, 40, 40).addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(18, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(31, 31, 31)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(adminP).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(adminM))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(adminL))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(
										jPanel1Layout.createSequentialGroup()
												.addComponent(magic, javax.swing.GroupLayout.DEFAULT_SIZE, 35,
														Short.MAX_VALUE)
												.addGap(3, 3, 3)))
						.addGap(34, 34, 34))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(adminTurn0, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(adminTurn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(adminTurn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(adminTurn3, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(
						jPanel1Layout.createSequentialGroup().addGap(29, 29, 29)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(adminSlot).addComponent(
														jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
																35, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(adminOwner))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
																35, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(adminPrice))
												.addContainerGap(74, Short.MAX_VALUE))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void confirmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmActionPerformed
		// TODO add your handling code here:
		boolean changeP = (!adminP.getText().equals("")) && (!adminM.getText().equals(""))
				&& (!adminL.getText().equals(""));
		boolean changeS = (!adminSlot.getText().equals("")) && (!adminOwner.getText().equals(""))
				&& (!adminPrice.getText().equals(""));

		if (changeP) {
			int p = Integer.parseInt(adminP.getText()) - 1;
			int m = Integer.parseInt(adminM.getText());
			int l = Integer.parseInt(adminL.getText());

			c.adminChangeP(p, m, l);
		}

		if (changeS) {
			int s = Integer.parseInt(adminSlot.getText());
			int o = Integer.parseInt(adminOwner.getText());
			int p = Integer.parseInt(adminPrice.getText());
			c.adminChangeS(s, o, p);
		}
	}// GEN-LAST:event_confirmActionPerformed

	private void adminTurn0ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminTurn0ActionPerformed
		// TODO add your handling code here:
		c.adminTurn(0);
	}// GEN-LAST:event_adminTurn0ActionPerformed

	private void adminTurn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminTurn1ActionPerformed
		// TODO add your handling code here:
		c.adminTurn(1);
	}// GEN-LAST:event_adminTurn1ActionPerformed

	private void adminTurn2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminTurn2ActionPerformed
		// TODO add your handling code here:
		c.adminTurn(2);
	}// GEN-LAST:event_adminTurn2ActionPerformed

	private void adminTurn3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminTurn3ActionPerformed
		// TODO add your handling code here:
		c.adminTurn(3);
	}// GEN-LAST:event_adminTurn3ActionPerformed

	private void magicActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_magicActionPerformed
		// TODO add your handling code here:
		int p = Integer.parseInt(adminP.getText()); // Assume they would always start inputting from 1
		c.changeStatus(p - 1);
	}// GEN-LAST:event_magicActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField adminL;
	private javax.swing.JTextField adminM;
	private javax.swing.JTextField adminOwner;
	private javax.swing.JTextField adminP;
	private javax.swing.JTextField adminPrice;
	private javax.swing.JTextField adminSlot;
	private javax.swing.JButton adminTurn0;
	private javax.swing.JButton adminTurn1;
	private javax.swing.JButton adminTurn2;
	private javax.swing.JButton adminTurn3;
	private javax.swing.JButton confirm;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton magic;
	// End of variables declaration//GEN-END:variables
}
